const today = new Date();
const formatDate = (d) => d.toISOString().split('T')[0];

function daysFromNow(n) {
  const d = new Date(today);
  d.setDate(d.getDate() + n);
  return d;
}

// --- Course 1: Algorithms ---
export const demoTopics = [
  {
    id: 1,
    name: 'מיון ואלגוריתמי חיפוש',
    subtopics: ['מיון בועות', 'מיון מהיר (Quicksort)', 'מיון מיזוג (Mergesort)', 'חיפוש בינארי'],
    syllabusWeight: 'high',
    examFrequency: 1.0,
    priorityScore: 1.0,
    estimatedHours: 12,
    status: 'completed',
    startWeek: 1,
    endWeek: 1,
    scheduledHours: 10,
  },
  {
    id: 2,
    name: 'עצים בינאריים',
    subtopics: ['עץ חיפוש בינארי (BST)', 'עצי AVL', 'סיבוכיות פעולות'],
    syllabusWeight: 'high',
    examFrequency: 0.67,
    priorityScore: 0.87,
    estimatedHours: 10,
    status: 'completed',
    startWeek: 1,
    endWeek: 1,
    scheduledHours: 8,
  },
  {
    id: 3,
    name: 'גרפים',
    subtopics: ['BFS', 'DFS', 'אלגוריתם דייקסטרה', 'מציאת מסלול קצר ביותר'],
    syllabusWeight: 'high',
    examFrequency: 0.67,
    priorityScore: 0.87,
    estimatedHours: 14,
    status: 'in_progress',
    startWeek: 2,
    endWeek: 2,
    scheduledHours: 12,
  },
  {
    id: 4,
    name: 'תכנות דינמי',
    subtopics: ['עקרון האופטימליות', 'בעיית התרמיל', 'סדרה משותפת ארוכה ביותר'],
    syllabusWeight: 'medium',
    examFrequency: 0.33,
    priorityScore: 0.49,
    estimatedHours: 10,
    status: 'not_started',
    startWeek: 2,
    endWeek: 3,
    scheduledHours: 8,
  },
  {
    id: 5,
    name: 'ערימות ותורי עדיפות',
    subtopics: ['ערימת מינימום', 'ערימת מקסימום', 'תור עדיפות'],
    syllabusWeight: 'medium',
    examFrequency: 0.33,
    priorityScore: 0.49,
    estimatedHours: 8,
    status: 'not_started',
    startWeek: 3,
    endWeek: 3,
    scheduledHours: 6,
  },
  {
    id: 6,
    name: 'סיבוכיות וסימון אסימפטוטי',
    subtopics: ['Big-O', 'Big-Ω', 'Big-Θ', 'חישוב סיבוכיות רקורסיבית'],
    syllabusWeight: 'low',
    examFrequency: 0.33,
    priorityScore: 0.31,
    estimatedHours: 6,
    status: 'not_started',
    startWeek: 3,
    endWeek: 3,
    scheduledHours: 5,
  },
];

// --- Course 2: Statistics ---
const statsTopics = [
  {
    id: 1,
    name: 'הסתברות בסיסית',
    subtopics: ['מרחב מדגם', 'הסתברות מותנית', 'נוסחת בייס', 'אי-תלות'],
    syllabusWeight: 'high',
    examFrequency: 0.8,
    priorityScore: 0.92,
    estimatedHours: 10,
    status: 'completed',
    startWeek: 1,
    endWeek: 1,
    scheduledHours: 8,
  },
  {
    id: 2,
    name: 'משתנים מקריים',
    subtopics: ['התפלגות בינומית', 'התפלגות פואסון', 'התפלגות נורמלית', 'תוחלת ושונות'],
    syllabusWeight: 'high',
    examFrequency: 0.9,
    priorityScore: 0.96,
    estimatedHours: 14,
    status: 'in_progress',
    startWeek: 1,
    endWeek: 2,
    scheduledHours: 12,
  },
  {
    id: 3,
    name: 'אמידה סטטיסטית',
    subtopics: ['אמידת נקודה', 'רווחי סמך', 'אמידת ML'],
    syllabusWeight: 'high',
    examFrequency: 0.7,
    priorityScore: 0.88,
    estimatedHours: 12,
    status: 'not_started',
    startWeek: 2,
    endWeek: 3,
    scheduledHours: 10,
  },
  {
    id: 4,
    name: 'בדיקות השערות',
    subtopics: ['מבחן Z', 'מבחן T', 'שגיאות סוג I ו-II', 'עוצמת מבחן'],
    syllabusWeight: 'medium',
    examFrequency: 0.6,
    priorityScore: 0.6,
    estimatedHours: 10,
    status: 'not_started',
    startWeek: 3,
    endWeek: 4,
    scheduledHours: 8,
  },
  {
    id: 5,
    name: 'רגרסיה לינארית',
    subtopics: ['רגרסיה פשוטה', 'רגרסיה מרובה', 'R²', 'שאריות'],
    syllabusWeight: 'medium',
    examFrequency: 0.5,
    priorityScore: 0.56,
    estimatedHours: 8,
    status: 'not_started',
    startWeek: 4,
    endWeek: 4,
    scheduledHours: 6,
  },
];

// --- Course 3: Linear Algebra ---
const linalgTopics = [
  {
    id: 1,
    name: 'מטריצות ופעולות',
    subtopics: ['חיבור מטריצות', 'כפל מטריצות', 'מטריצה הפוכה', 'דטרמיננטה'],
    syllabusWeight: 'high',
    examFrequency: 1.0,
    priorityScore: 1.0,
    estimatedHours: 10,
    status: 'completed',
    startWeek: 1,
    endWeek: 1,
    scheduledHours: 8,
  },
  {
    id: 2,
    name: 'מרחבים וקטוריים',
    subtopics: ['תת-מרחב', 'בסיס וממד', 'תלות לינארית', 'פריסה'],
    syllabusWeight: 'high',
    examFrequency: 0.85,
    priorityScore: 0.94,
    estimatedHours: 14,
    status: 'completed',
    startWeek: 1,
    endWeek: 2,
    scheduledHours: 12,
  },
  {
    id: 3,
    name: 'העתקות לינאריות',
    subtopics: ['מטריצת ייצוג', 'גרעין ותמונה', 'איזומורפיזם'],
    syllabusWeight: 'high',
    examFrequency: 0.7,
    priorityScore: 0.88,
    estimatedHours: 12,
    status: 'completed',
    startWeek: 2,
    endWeek: 2,
    scheduledHours: 10,
  },
  {
    id: 4,
    name: 'ערכים עצמיים ולכסון',
    subtopics: ['פולינום אופייני', 'וקטורים עצמיים', 'לכסון מטריצות'],
    syllabusWeight: 'high',
    examFrequency: 0.9,
    priorityScore: 0.96,
    estimatedHours: 12,
    status: 'in_progress',
    startWeek: 3,
    endWeek: 3,
    scheduledHours: 10,
  },
  {
    id: 5,
    name: 'מכפלה פנימית',
    subtopics: ['מרחב מכפלה פנימית', 'תהליך גרם-שמידט', 'מטריצות אורתוגונליות'],
    syllabusWeight: 'medium',
    examFrequency: 0.5,
    priorityScore: 0.56,
    estimatedHours: 8,
    status: 'not_started',
    startWeek: 3,
    endWeek: 3,
    scheduledHours: 6,
  },
];

export const demoCourseData = {
  id: 'course-1',
  courseName: 'אלגוריתמים ומבנה נתונים',
  examDate: formatDate(daysFromNow(21)),
  hoursPerWeek: 10,
  topics: demoTopics,
  pastExamsCount: 3,
  priority: 'high',
};

export const demoCoursesData = [
  demoCourseData,
  {
    id: 'course-2',
    courseName: 'הסתברות וסטטיסטיקה',
    examDate: formatDate(daysFromNow(30)),
    hoursPerWeek: 8,
    topics: statsTopics,
    pastExamsCount: 2,
    priority: 'high',
  },
  {
    id: 'course-3',
    courseName: 'אלגברה לינארית 2',
    examDate: formatDate(daysFromNow(12)),
    hoursPerWeek: 12,
    topics: linalgTopics,
    pastExamsCount: 4,
    priority: 'medium',
  },
];

export const demoParsedResult = {
  courseName: 'אלגוריתמים ומבנה נתונים',
  topics: demoTopics.map(({ id, name, subtopics, syllabusWeight, examFrequency, priorityScore, estimatedHours }) => ({
    id,
    name,
    subtopics,
    syllabusWeight,
    examFrequency,
    priorityScore,
    estimatedHours,
  })),
};
