const formatDate = (d) => d.toISOString().split('T')[0];

// --- Course 1: Numerical Analysis ---
const numericalTopics = [
  {
    id: 1,
    name: 'אינטרפולציה',
    subtopics: ['פולינום אינטרפולציה: קיום ויחידות', 'שיטת לגרנז\'', 'שיטת ניוטון — הפרשים מחולקים', 'אינטרפולציית הרמיט', 'ספליין הרמיטי', 'הערכת שגיאה R_n(x)'],
    syllabusWeight: 'high',
    examFrequency: 1.0,
    priorityScore: 1.0,
    estimatedHours: 14,
    status: 'completed',
  },
  {
    id: 2,
    name: 'אינטגרציה נומרית',
    subtopics: ['שיטת מלבן / נקודת אמצע / טרפז / סימפסון', 'שגיאות: O(h²) לטרפז, O(h⁴) לסימפסון', 'נוסחאות מרוכבות', 'אינטגרציית גאוס-לז\'נדר', 'אינטגרציית גאוס-צ\'ביצ\'ב', 'קירוב ריבועים מינימלי'],
    syllabusWeight: 'high',
    examFrequency: 1.0,
    priorityScore: 1.0,
    estimatedHours: 12,
    status: 'completed',
  },
  {
    id: 3,
    name: 'משוואות דיפרנציאליות רגילות (מד"ר)',
    subtopics: ['שיטת אוילר — שגיאה O(h)', 'שיטות טיילור (סדר גבוה)', 'רונגה-קוטה (RK4)', 'שיטות סתומות (Implicit Euler, Trapezoidal)', 'שגיאה לוקלית vs. גלובלית'],
    syllabusWeight: 'high',
    examFrequency: 0.9,
    priorityScore: 0.96,
    estimatedHours: 10,
    status: 'in_progress',
  },
  {
    id: 4,
    name: 'משוואות לא-ליניאריות',
    subtopics: ['שיטת החציה', 'ניוטון-רפסון', 'שיטת המיתר (Secant)', 'נקודת שבת: תנאי התכנסות', 'סדר התכנסות של כל שיטה'],
    syllabusWeight: 'high',
    examFrequency: 0.8,
    priorityScore: 0.92,
    estimatedHours: 8,
    status: 'not_started',
  },
  {
    id: 5,
    name: 'מערכות ליניאריות',
    subtopics: ['שיטת דירוג גאוס + הצרה חלקית', 'פירוק LU (עם/בלי הצרה)', 'שיטות איטרטיביות: יעקובי, גאוס-זיידל', 'מספר מצב (Condition Number)'],
    syllabusWeight: 'medium',
    examFrequency: 0.7,
    priorityScore: 0.64,
    estimatedHours: 8,
    status: 'not_started',
  },
  {
    id: 6,
    name: 'גזירה נומרית',
    subtopics: ['גזירת פולינום האינטרפולציה', 'שיטת טיילור לקירוב נגזרת', 'הערכת שגיאת קיטוע'],
    syllabusWeight: 'low',
    examFrequency: 0.5,
    priorityScore: 0.38,
    estimatedHours: 6,
    status: 'not_started',
  },
];

// --- Course 2: Psychology ---
const psychTopics = [
  {
    id: 1,
    name: 'למידה',
    subtopics: ['התניה קלאסית (פבלוב) — CS, UCS, CR, UCR, הכחדה, הכללה', 'התניה אופרנטית (סקינר) — חיזוק חיובי/שלילי, עונש, לוחות חיזוק', 'למידה חברתית (בנדורה) — מודלינג, self-efficacy', 'יישום בארגון: הכשרה, תגמולים, בטיחות'],
    syllabusWeight: 'high',
    examFrequency: 0.9,
    priorityScore: 0.96,
    estimatedHours: 8,
    status: 'in_progress',
  },
  {
    id: 2,
    name: 'אבחון — אישיות ויכולות קוגניטיביות',
    subtopics: ['Big Five (OCEAN)', 'טיפוסי MBTI', 'אמינות ותקפות מבחנים', 'g factor ויכולות ספציפיות', 'שימוש בבחירת עובדים ומיון'],
    syllabusWeight: 'high',
    examFrequency: 0.8,
    priorityScore: 0.92,
    estimatedHours: 8,
    status: 'not_started',
  },
  {
    id: 3,
    name: 'פסיכולוגיה קוגניטיבית',
    subtopics: ['עיבוד מידע כמטאפורה', 'תפיסה — עקרונות גשטלט, תפיסת עומק, אשליות', 'קשב — קשב מוחלק/מפוצל, bottleneck, workload', 'זיכרון — זיכרון עבודה (Miller: 7±2), זיכרון לטווח ארוך, שכחה'],
    syllabusWeight: 'high',
    examFrequency: 0.85,
    priorityScore: 0.94,
    estimatedHours: 10,
    status: 'not_started',
  },
  {
    id: 4,
    name: 'פסיכולוגיה חברתית + עבודה',
    subtopics: ['עצמי חברתי — זהות חברתית, קבוצות', 'שכנוע, הסכמה וציות — Milgram, Asch, Cialdini', 'לחץ וחרדה בעבודה — burnout, stressors, coping', 'פסיכופתולוגיה — הפרעות רלוונטיות לעבודה'],
    syllabusWeight: 'medium',
    examFrequency: 0.7,
    priorityScore: 0.64,
    estimatedHours: 8,
    status: 'not_started',
  },
];

// --- Course 3: Methods Engineering ---
const methodsTopics = [
  {
    id: 1,
    name: 'ניהול רזה + תרשימים',
    subtopics: ['עקרונות Lean: 8 הבזבוזים, Value Stream', 'מדדי פריון: יעילות, תפוקה, OEE', 'תרשים תהליך, תרשים תעסוקה (Man-Machine)', 'ניתוח פעילויות — ערך מוסף vs. לא'],
    syllabusWeight: 'medium',
    examFrequency: 0.6,
    priorityScore: 0.6,
    estimatedHours: 6,
    status: 'in_progress',
  },
  {
    id: 2,
    name: 'חקר זמן ישיר',
    subtopics: ['מחזורי: זמן נצפה → זמן נורמלי → זמן תקן', 'שיקולים סטטיסטיים: n = (z·s / e·x̄)²', 'חקר זמן אקראי (Random Snap-back)', 'נוסחת זמן תקן: NT = OT × PR | ST = NT × (1 + allowance)'],
    syllabusWeight: 'high',
    examFrequency: 0.9,
    priorityScore: 0.96,
    estimatedHours: 10,
    status: 'not_started',
  },
  {
    id: 3,
    name: 'דגימת עבודה',
    subtopics: ['רב תצפיתי — אחוזי פעילות', 'n = (z/e)² · p·(1-p)', 'ב.ס. לאחוז: p ± z·√(p(1-p)/n)'],
    syllabusWeight: 'high',
    examFrequency: 0.8,
    priorityScore: 0.92,
    estimatedHours: 6,
    status: 'not_started',
  },
  {
    id: 4,
    name: 'אדם-מכונה + עקומות למידה',
    subtopics: ['דטרמיניסטי: n = (L+M)/(L+W)', 'סטוכסטי: תורים + MTBF/MTTR', 'עקומת למידה: Y_n = Y_1 · n^b', 'עלות הכשרה + השפעה על תפוקה', 'מערכות שכר עידוד'],
    syllabusWeight: 'high',
    examFrequency: 0.85,
    priorityScore: 0.94,
    estimatedHours: 8,
    status: 'not_started',
  },
];

// --- Course 4: Algorithms ---
const algoTopics = [
  {
    id: 1,
    name: 'רקורסיה + סיבוכיות',
    subtopics: ['רקורסיה בסיסית: base case, recursive case', 'Divide & Conquer: Merge Sort, Binary Search', 'Memoization + Dynamic Programming', 'Big-O: O(1), O(log n), O(n), O(n log n), O(n²)', 'השוואת אלגוריתמי מיון'],
    syllabusWeight: 'high',
    examFrequency: 1.0,
    priorityScore: 1.0,
    estimatedHours: 10,
    status: 'in_progress',
  },
  {
    id: 2,
    name: 'מבני נתונים',
    subtopics: ['Linked List: insert, delete, search', 'Stack (LIFO): push, pop', 'Queue (FIFO): enqueue, dequeue', 'Binary Tree: Preorder / Inorder / Postorder / BFS', 'גרפים: adjacency list/matrix, DFS, BFS'],
    syllabusWeight: 'high',
    examFrequency: 0.9,
    priorityScore: 0.96,
    estimatedHours: 10,
    status: 'not_started',
  },
  {
    id: 3,
    name: 'pandas',
    subtopics: ['יצירת DataFrame מ-dict / קריאה מ-CSV', 'סינון ומיון', 'ערכים חסרים: isnull(), fillna(), dropna()', 'groupby + agg', 'merge/join', 'apply + lambda'],
    syllabusWeight: 'high',
    examFrequency: 0.85,
    priorityScore: 0.94,
    estimatedHours: 8,
    status: 'not_started',
  },
];

// --- Course 5: Quality Assurance ---
const qualityTopics = [
  {
    id: 1,
    name: 'מבוא ו-DMAIC',
    subtopics: ['TQM, Six Sigma (DMAIC, DMADV)', 'ISO 9000 — עקרונות', 'עלויות איכות: prevention, appraisal, failure', '7 כלים: Pareto, Ishikawa, Control Chart, Histogram, Scatter, Check Sheet, Flow'],
    syllabusWeight: 'medium',
    examFrequency: 0.6,
    priorityScore: 0.6,
    estimatedHours: 6,
    status: 'in_progress',
  },
  {
    id: 2,
    name: 'SPC — תרשימי בקרה למשתנים',
    subtopics: ['X̄-R chart: UCL/LCL', 'X̄-S chart: UCL/LCL', 'עקומת OC', 'כללי Western Electric', 'אמידת σ מ-R̄ ו-S̄'],
    syllabusWeight: 'high',
    examFrequency: 0.95,
    priorityScore: 0.98,
    estimatedHours: 12,
    status: 'not_started',
  },
  {
    id: 3,
    name: 'SPC — לתכונות + מתקדם',
    subtopics: ['p-chart (שיעור פגומים)', 'c-chart (מספר פגמים)', 'u-chart (פגמים ליחידה)', 'EWMA', 'CUSUM'],
    syllabusWeight: 'high',
    examFrequency: 0.85,
    priorityScore: 0.94,
    estimatedHours: 10,
    status: 'not_started',
  },
  {
    id: 4,
    name: 'כושר תהליך + אמינות',
    subtopics: ['Cp = (USL-LSL)/(6σ)', 'Cpk = min[(USL-μ)/3σ, (μ-LSL)/3σ]', 'Cpm — סטייה מיעד', '% פגומים מהתפלגות נורמלית', 'MSA: Gauge R&R — ANOVA', 'אמינות: R(t) = e^(-λt)', 'מערכות סדרה, מקבילה, מעורבת'],
    syllabusWeight: 'high',
    examFrequency: 0.9,
    priorityScore: 0.96,
    estimatedHours: 10,
    status: 'not_started',
  },
  {
    id: 5,
    name: 'דגימת קבלה',
    subtopics: ['תוכנית חד-שלבית: (n, c)', 'דו-שלבית: ניתוח ASN', 'MIL-STD-105E: AQL → טבלאות', 'MIL-STD-414: דגימה לפי משתנים', 'AOQ, AOQL', 'עקומת OC: Pa(p)'],
    syllabusWeight: 'medium',
    examFrequency: 0.7,
    priorityScore: 0.64,
    estimatedHours: 8,
    status: 'not_started',
  },
];

// --- Course 6: Operations Management ---
const opsTopics = [
  {
    id: 1,
    name: 'חיזוי',
    subtopics: ['ממוצע נע רגיל ומשוקלל', 'החלקה מעריכית', 'החלקה כפולה (מגמה) — Brown/Holt', 'מודלים עם עונתיות', 'מדדי שגיאה: MAD, MAPE, MSE, Tracking Signal', 'רגרסיה ליניארית'],
    syllabusWeight: 'high',
    examFrequency: 0.9,
    priorityScore: 0.96,
    estimatedHours: 10,
    status: 'in_progress',
  },
  {
    id: 2,
    name: 'תכנון מצרפי',
    subtopics: ['מדיניות רדיפת ביקוש (Chase)', 'מדיניות כוח אדם קבוע (Level)', 'מדיניות ביניים', 'תכנות ליניארי לאופטימיזציה', 'עלויות: שכר, גיוס, פיטורים, מלאי, חוסר'],
    syllabusWeight: 'high',
    examFrequency: 0.85,
    priorityScore: 0.94,
    estimatedHours: 10,
    status: 'not_started',
  },
  {
    id: 3,
    name: 'EOQ ומשפחתו',
    subtopics: ['EOQ = √(2DS/H)', 'EPQ (ייצור)', 'עם חוסר (Shortage allowed)', 'הנחה על כל הכמות', 'הנחה מדורגת', 'מוצרים מרובים: אילוץ תקציב/שטח', 'מחזור משותף'],
    syllabusWeight: 'high',
    examFrequency: 1.0,
    priorityScore: 1.0,
    estimatedHours: 10,
    status: 'not_started',
  },
  {
    id: 4,
    name: 'MRP + ביקוש אקראי',
    subtopics: ['MRP: עץ מוצר → BOM → Gross/Net Requirements', 'שיטות גדלי הזמנה: LFL, EOQ, Silver-Meal, LUC, PPB', 'מוכר העיתונים: Q* = F⁻¹(Cᵤ/(Cᵤ+Cₒ))', 'מודל QR: R = μ_LT + z·σ_LT', 'רמת שירות סוג 1 vs. סוג 2', 'Loss Function: E[max(D-R,0)] = σ·L(z)', 'מודל (s,S) ו-T'],
    syllabusWeight: 'high',
    examFrequency: 0.95,
    priorityScore: 0.98,
    estimatedHours: 12,
    status: 'not_started',
  },
];

// --- Course data objects ---
export const demoCourseData = {
  id: 'course-1',
  courseName: 'אנליזה נומרית',
  examDate: '2026-07-13',
  hoursPerWeek: 8,
  topics: numericalTopics,
  pastExamsCount: 4,
  priority: 'high',
};

export const demoCoursesData = [
  demoCourseData,
  {
    id: 'course-2',
    courseName: 'מבוא לפסיכולוגיה ניסויית ותעשייתית',
    examDate: '2026-07-16',
    hoursPerWeek: 6,
    topics: psychTopics,
    pastExamsCount: 0,
    priority: 'high',
  },
  {
    id: 'course-3',
    courseName: 'הנדסת שיטות',
    examDate: '2026-07-19',
    hoursPerWeek: 6,
    topics: methodsTopics,
    pastExamsCount: 2,
    priority: 'medium',
  },
  {
    id: 'course-4',
    courseName: 'אלגוריתמים ומבנה נתונים',
    examDate: '2026-07-22',
    hoursPerWeek: 6,
    topics: algoTopics,
    pastExamsCount: 3,
    priority: 'high',
  },
  {
    id: 'course-5',
    courseName: 'אבטחת איכות',
    examDate: '2026-07-26',
    hoursPerWeek: 6,
    topics: qualityTopics,
    pastExamsCount: 2,
    priority: 'medium',
  },
  {
    id: 'course-6',
    courseName: 'ניהול התפעול 1',
    examDate: '2026-07-30',
    hoursPerWeek: 6,
    topics: opsTopics,
    pastExamsCount: 3,
    priority: 'medium',
  },
];

export const demoParsedResult = {
  courseName: 'אנליזה נומרית',
  topics: numericalTopics.map(({ id, name, subtopics, syllabusWeight, examFrequency, priorityScore, estimatedHours }) => ({
    id, name, subtopics, syllabusWeight, examFrequency, priorityScore, estimatedHours,
  })),
};
